apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: spring-boot-monitor
  namespace: default  # 🔴 Le ServiceMonitor est dans default !
  labels:
    release: prometheus  # 🔴 Ce label est OBLIGATOIRE !
spec:
  selector:
    matchLabels:
      app: spring-boot-app  # Doit correspondre aux labels du Service
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s

